name: yatr
on:
  - push

jobs:
  yatr:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt install -y bison flex texinfo help2man libtool-bin libncurses-dev

      - name: Run yatr
        env:
          TARGET: dist-linux-amd64
          CT_NG_COMMIT: "8fa98eeeff9bc53478d97ef722f366fea151ae64"
          AVR_DX_PACK_VERSION: "2.1.146"
          DISTFILES_URL: "${{ secrets.DISTFILES_URL }}"
        run: curl -sSf https://yatr.rgm.io/run.sh | bash
